# TouchDesigner YOLO Environment Configuration
# ===============================================
# This file defines the conda environment for TouchDesigner YOLO integration
# 
# Usage:
#   conda env create -n yolo11-TD -f environment_optimized.yml
#   conda env create -n custom-name -f environment_optimized.yml
#
channels:
  - conda-forge
  - pytorch
dependencies:
  # Base Python and system libraries
  - python=3.11.10
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13

  # PyTorch with MPS support for Mac, and CUDA for Linux/Windows
  - pytorch=2.7.1
  - torchvision=0.22.1
  - torchaudio=2.7.1

  # Core scientific computing
  - numpy=2.3.1
  - scipy=1.16.0

  # Additional conda packages for better performance
  - mkl=2024.1.0  # Intel Math Kernel Library for faster numpy operations
  - mkl-service=2.4.0

  - pip:
      # Computer Vision
      - opencv-python==4.11.0.86
      - pillow==11.2.1

      # YOLO and AI
      - ultralytics==8.3.159
      - ultralytics-thop==2.0.14

      # TouchDesigner compatibility
      - pywin32==306; sys_platform == "win32"  # Windows only
      - psutil==7.0.0

      # Data handling
      - pandas==2.3.0
      - matplotlib==3.10.3

      # Networking and utilities  
      - requests==2.32.4
      - urllib3==2.5.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - idna==3.10

      # Parsing and formatting
      - pyyaml==6.0.2
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - packaging==25.0
      - setuptools==80.9.0

      # Progress and monitoring
      - tqdm==4.67.1
      - py-cpuinfo==9.0.0

      # Math and symbolic computation
      - sympy==1.14.0
      - mpmath==1.3.0
      - networkx==3.5

      # Plotting utilities
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.4
      - kiwisolver==1.4.8
      - pyparsing==3.2.3

      # Date and time
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - tzdata==2025.2

      # System utilities
      - filelock==3.18.0
      - fsspec==2025.5.1
      - typing-extensions==4.14.0
      - six==1.17.0

      # TouchDesigner specific optimizations
      - numba==0.60.0  # JIT compilation for faster numpy operations
      - scikit-image==0.24.0  # Advanced image processing
      - imageio==2.36.1  # Image I/O operations

      # Optional: GPU monitoring (useful for debugging)
      - py3nvml==0.2.7  # NVIDIA GPU monitoring (if applicable)
